export {default as Home} from "./home/Home"
export {default as SignIn} from "./signIn/SignIn"
export {default as Dashboard} from "./dashboard/Dashboard"
export {default as Profile} from "./profile/Profile"
export {default as TakeAttendanceForm} from "./takeAttendance/TakeAttendanceForm"
export {default as ReportForm} from "./report/ReportForm"
export {default as StudentStats} from "./report/StudentStats"
export {default as SingleCourseList} from "./singleCourseList/SingleCourseList"